var app = angular.module('myApp', []);
app.controller('Ctrl', function($scope) {
    $scope.isban = {
        logo:"Company Logo",
        username_text:"Username",
        username:"Mr Joe Bloggs",
        username_dob:"24 Abr 1942",
        username_address:"12 Address City,AB1 2CD",
        username_type:"Type",
        nav_micro_text:"MIRO cases",
        nav_information_text:"Information",
        nav_information_value:"3",
        nav_notes_text:"Notes",
        carousel_one_text:"Carousel 1",
        carousel_two_text:"Carousel 2",
        carousel_ribbon_negative:"Negative title",
        carousel_ribbon_positive:"Positive title",
        carousel_text:"Lorem ipsum dolor amet, consectetur",
        isban_button_text:"Button",
        isban_button_text_xs:"Button1",
        isban_button_text_ms:"Button2",
        isban_product_text:"Products",
        isban_product_text_one:"1",
        isban_product_text_two:"2",
        isban_product_one_text:"Product 1",
        isban_product_one_price:"22,872",
        isban_product_three_price:"5,700",
        isban_product_four_price:"1,231",
        isban_product_eight_price:"18,700",
        isban_product_nine_price:"18,700",
        isban_product_two_text:"Product 2",
        isban_product_three_text:"Product 3",
        isban_product_four_text:"Product 4",
        isban_product_five_text:"Product 5",
        isban_product_six_text:"Product 6",
        isban_product_seven_text:"Product 7",
        isban_product_eight_text:"Product 8",
        isban_product_nine_text:"Product 9",
        isban_product_ten_text:"Product 10",
        appointment_date_one:"7th January",
        appointment_subText_one:"Appointment line 1",
        appointment_subText_two:"Appointment line 2",
        appointment_date_two:"10th January",
        appointment_date_three:"13th January",
        appointment_date_four:"13 January",
        appointment_date_five:"Today 10:30pm"
    }
});